name: CI

on:
  push:
    branches: [ "*" ]

jobs:
  ci:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - uses: golangci/golangci-lint-action@v6
        with:
          install-mode: binary
          version: latest
